// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCXZectGSmIxImrEN2CcrTajfypNDNbgEY',
    appId: '1:788918028439:web:e895c49a3ec46f059601d2',
    messagingSenderId: '788918028439',
    projectId: 'flutter-data-display-78ed4',
    authDomain: 'flutter-data-display-78ed4.firebaseapp.com',
    storageBucket: 'flutter-data-display-78ed4.appspot.com',
    measurementId: 'G-R2239VL4H9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB1DptIkF7-lwgR09fwWyJq8Z2gEdKRbLM',
    appId: '1:788918028439:android:d1922c113bcc27139601d2',
    messagingSenderId: '788918028439',
    projectId: 'flutter-data-display-78ed4',
    storageBucket: 'flutter-data-display-78ed4.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCdO36XjlTAahl2YCfY3Tzr8KR-lPPnVHA',
    appId: '1:788918028439:ios:5f3b94d6d56f16ce9601d2',
    messagingSenderId: '788918028439',
    projectId: 'flutter-data-display-78ed4',
    storageBucket: 'flutter-data-display-78ed4.appspot.com',
    iosBundleId: 'com.example.dataDisplayApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCdO36XjlTAahl2YCfY3Tzr8KR-lPPnVHA',
    appId: '1:788918028439:ios:5f3b94d6d56f16ce9601d2',
    messagingSenderId: '788918028439',
    projectId: 'flutter-data-display-78ed4',
    storageBucket: 'flutter-data-display-78ed4.appspot.com',
    iosBundleId: 'com.example.dataDisplayApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCXZectGSmIxImrEN2CcrTajfypNDNbgEY',
    appId: '1:788918028439:web:57b3c99a9bed91329601d2',
    messagingSenderId: '788918028439',
    projectId: 'flutter-data-display-78ed4',
    authDomain: 'flutter-data-display-78ed4.firebaseapp.com',
    storageBucket: 'flutter-data-display-78ed4.appspot.com',
    measurementId: 'G-SDWDEYJ7XH',
  );
}
